import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "../(dashboard)/(home)/globals.css";
import BootstrapClient from "@/lib/layout/BootstrapClient";
import Navbar from "@/lib/layout/Navbar";
import {ToastContainer} from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <link rel="stylesheet"
            href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"/>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Navbar/>
      {children}
      <ToastContainer/>
      <BootstrapClient/>
      </body>
      </html>
  );
}
